### ISSUE TITLE
Accounts not showing

### ISSUE THREAD

**Issue by k1ng-ra3d** [NanoSoftwares/Scraper#2]
Whenever I press start it shows, couldnt scrape any links, then it shows got 10 links only once, and the accounts never show. 
![image](https://user-images.githubusercontent.com/64957600/111037902-1a4be980-841e-11eb-9155-019d70a85af0.png)

**Comment by AnErrupTion** [comment]
That may be due to the fact that you're IP is blacklisted, or worse, your ISP blacklists some websites. But in most cases using a VPN or proxies should fix the issues. Since you seem to be using default configuration, that can't be the problem.

**Comment by ztKaizen** [comment]
Not running on my Windows 10 Pro (12GB RAM i5)
I tried installing the things on the readme but still not working.

**Comment by epyklion** [comment]
Hey check settings.txt in the settings folder and change the regex according to what you want. It should like this if you want email:pass combos or similar to that.
Image: https://ibb.co/9hH1n6B
Hope this helped
